/**
 * Created by ESC on 2017/9/7.
 */
$(function () {

  var data={
    "classification":
    {
      "name":"familyClear",
      "itemName":"家庭保洁",

      "items":[{
      "name":"小时工",
      "itemName":"hourWork"
    },
      {
        "name":"开荒保洁",
        "itemName":"keepClear"
      },
      {
        "name":"擦玻璃",
        "itemName":"clearWindow"
      },
      {
        "name":"深度保洁",
        "itemName":"deepClear"
      },
      {
        "name":"家居养护",
        "itemName":"clearHotel"
      },
      {
        "name":"杀虫除螨",
        "itemName":"killWorm"
      }],
      "data":[
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/26/c01a93eb-01ec-468c-a2ec-1c78f8247b67_thumb.jpg",
        "title": "4小时专业擦玻璃",
        "description": "服务内容：1.专业擦玻璃，共4小时，服务商携带工具上门。...",
        "price": "159",
        "oldPrice": "300元",
        "discount": true,
        "unit": "元/4小时",
        "serveName": "三鼎家政",
        "allSellsCount": "1983",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/a3d7f941-9412-4963-9144-8cbcce09f610_thumb.jpg",
        "title": "玻璃清洁（101-260平）",
        "description": "服务内容：本服务产品主要将潜伏在门窗边框及窗槽内的细菌、霉...",
        "price": "599",
        "oldPrice": "699元",
        "discount": true,
        "unit": "元/次",
        "serveName": "580家政网",
        "allSellsCount": "2",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/07/21/aa18e1d1-845d-4cb4-9b1b-237c34cc2f8f_thumb.jpg",
        "title": "专业玻璃清洗（含纱窗）",
        "description": "40分钟速达安全快捷（按居室户型计算均可），专业技师，专...",
        "price": "29",
        "oldPrice": "35元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "432",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/08/e74da0d8-99a2-442b-96a9-4c100fc779df_thumb.jpg",
        "title": "4h保洁+4h擦玻璃",
        "description": "服务内容：1.保洁+擦玻璃，服务商携带清洁装备，包含：清洁...",
        "price": "309",
        "oldPrice": "380元",
        "discount": true,
        "unit": "元/次",
        "serveName": "三鼎家政",
        "allSellsCount": "78",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/02/04/50f1da9d-1746-4696-963c-8095cb97a421_thumb.jpg",
        "title": "4h保洁+4h擦玻璃",
        "description": "服务内容：1.保洁+擦玻璃，服务商携带清洁装备，包含：清洁...",
        "price": "339",
        "oldPrice": "500元",
        "discount": true,
        "unit": "元/套",
        "serveName": "来人到家",
        "allSellsCount": "554",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/0c6c2cfd-0446-48c1-998f-78f7cabe4ef8_thumb.jpg",
        "title": "玻璃深度清洁（100平以下）",
        "description": "服务内容：本服务产品主要将潜伏在门窗边框及窗槽内的细菌、霉...",
        "price": "399",
        "oldPrice": "499元",
        "discount": true,
        "unit": "元/次",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/8a867c01-8bd5-4d87-9c4e-deac3aaaf06d_thumb.jpg",
        "title": "玻璃清洁（261-400平）",
        "description": "服务内容：1.本服务主要将潜伏在门窗边框及窗槽内的细菌、霉...",
        "price": "799",
        "oldPrice": "999元",
        "discount": true,
        "unit": "元/次",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/09/01/13946f92-8ab6-4462-ab20-77338ff2b08f_thumb.jpg",
        "title": "1580元大直抵5360元礼包",
        "description": "礼包详情：价值1580元的服务礼包，下列3项产品任选4次，...",
        "price": "1580",
        "oldPrice": "5360元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/31/eac1ba06-23fe-4035-8408-0d6d5227327d_thumb.jpg",
        "title": "专业内外玻璃清洁",
        "description": "准备工具：准备工具：洗洁精、玻璃水、双面擦、水桶*2、百洁布...",
        "price": "15",
        "oldPrice": "20元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "十分到家",
        "allSellsCount": "0",
        "goodComment": "96%",
        "arriveTime": "18小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/1da14127-c0c5-4d2b-806f-a84eaad703da_thumb.jpg",
        "title": "外墙清洗",
        "description": "安全高效高质量服务内容：大型建筑、厂房厂区外墙...",
        "price": "5",
        "oldPrice": "10元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "1",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/12/19/66e4109e-1001-49a6-9a00-a227285cace6_thumb.jpg",
        "title": "三居室擦玻璃",
        "description": "服务范围：居室窗户1.玻璃边框、槽道无尘无水印2.玻璃...",
        "price": "599",
        "oldPrice": "700元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/12/19/b8237a78-fc20-4fba-a265-c29cc58c9b8e_thumb.jpg",
        "title": "四居室擦玻璃",
        "description": "服务范围：居室窗户1.玻璃边框、槽道无尘无水印2.玻璃...",
        "price": "698",
        "oldPrice": "800元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/12/19/73e3fe36-a35c-4cc9-9f90-3dfce846404c_thumb.jpg",
        "title": "别墅擦玻璃",
        "description": "服务范围：居室窗户1.玻璃边框、槽道无尘无水印2.玻璃...",
        "price": "1299",
        "oldPrice": "1599元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "4",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/04/17/de65ed71-8a27-4b71-bce1-10d2042d7027_thumb.jpg",
        "title": "空调清洗 普通柜机+2台挂机",
        "description": "服务内容:蒸发器、风筒、摆风叶片、接水槽、过滤网、外观清洁...",
        "price": "209",
        "oldPrice": "257元",
        "discount": true,
        "unit": "元/次",
        "serveName": "小蜜蜂维保汇",
        "allSellsCount": "0",
        "goodComment": "92%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/10/27/96c77187-ee06-431b-b733-8eb102ea7fa3_thumb.jpg",
        "title": "e家洁擦玻璃",
        "description": "服务内容：擦玻璃清洗服务，专业清洗人员上门服务，工作人员携...",
        "price": "13",
        "oldPrice": "13元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "e家洁",
        "allSellsCount": "22",
        "goodComment": "84%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/18/ef485b41-3ca8-49d0-b9ab-e289880575ac_thumb.jpg",
        "title": "4小时玻璃清洁",
        "description": "4小时起购，服务人员携带七色保洁布、进口工具组、多用玻璃擦、...",
        "price": "199",
        "oldPrice": "239元",
        "discount": true,
        "unit": "元/4小时",
        "serveName": "爱家管家",
        "allSellsCount": "0",
        "goodComment": "66%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/07/4483d722-566f-4a1b-938c-2ab0219f1a49_thumb.jpg",
        "title": "开荒保洁1平方（30平起拍）",
        "description": "服务内容：开荒保洁，30平米起购，服务商携带专业开荒工具上...",
        "price": "8",
        "oldPrice": "10元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "来人到家",
        "allSellsCount": "4181",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/24/923ee63e-498f-4a22-808c-f3c18946a307_thumb.jpg",
        "title": "开荒保洁1平方（30平起拍）",
        "description": "服务内容：开荒保洁，30平米起购，服务商携带专业开荒工具上...",
        "price": "8",
        "oldPrice": "12元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "三鼎家政",
        "allSellsCount": "1554",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/afab6e2b-3d3c-4085-aad1-6d8313487688_thumb.jpg",
        "title": "新居专业开荒",
        "description": "服务内容：本服务产品属于装修后的首次开荒保洁，60平米起...",
        "price": "18",
        "oldPrice": "25元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "580家政网",
        "allSellsCount": "473",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/19/91b5677b-ee18-441f-85dc-7a9aced77b9b_thumb.jpg",
        "title": "新居开荒",
        "description": "所谓无忧开荒是装修后的首次开荒保洁，属于精细开荒，均由经过专...",
        "price": "9",
        "oldPrice": "9元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "家事无忧",
        "allSellsCount": "1",
        "goodComment": "100%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/07/26/4e09bd77-e161-494f-856d-cd32980a5660_thumb.jpg",
        "title": "对公开荒保洁",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "5.5",
        "oldPrice": "7.5元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "1880",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/1bc8113a-b68b-4be2-aee4-55f49a3075b1_thumb.jpg",
        "title": "140平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1399",
        "oldPrice": "1400元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/e8d7e9ed-e7e3-4bb3-b74d-1c89223fcd7d_thumb.jpg",
        "title": "150平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1499",
        "oldPrice": "1500元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "2",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/4774e0ec-ada3-4c2a-97de-212ca8cf8801_thumb.jpg",
        "title": "200平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1999",
        "oldPrice": "2000元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/03/1d937c80-c243-4f17-b07e-c4a95992c22a_thumb.jpg",
        "title": "开荒保洁",
        "description": "服务内容：专业技师，专业设备，小圈为您提供最优秀的清洁服务...",
        "price": "10",
        "oldPrice": "10元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "250",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/05/16/78950d2b-132b-4953-b621-5db38685b52e_thumb.jpg",
        "title": "二手房开荒",
        "description": "服务内容：旧居开荒保洁服务，专业技师，专业设备，小圈为您提...",
        "price": "12",
        "oldPrice": "15元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "127",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/23/d177d0db-6d7b-41d2-8660-a6e61541b46c_thumb.jpg",
        "title": "新居精品开荒保洁",
        "description": "随叫随到，360度无死角精品开荒清洁自带所有工具和机器新...",
        "price": "12",
        "oldPrice": "15元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/06/15/1a8ffe69-dd9c-4a3c-ae86-cbdd702713fb_thumb.jpg",
        "title": "新居开荒",
        "description": "服务内容：新居装修入住前以及二手房翻新清洁，30平米起购（...",
        "price": "12",
        "oldPrice": "13元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "e家帮",
        "allSellsCount": "41",
        "goodComment": "87%",
        "arriveTime": "5小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/05/09/59e286bf-0f42-42d3-99ac-c93493a34f74_thumb.jpg",
        "title": "新居开荒保洁",
        "description": "服务内容：1.开荒服务按照建筑面积计算，60平米起订；...",
        "price": "8.8",
        "oldPrice": "12元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "e清洗",
        "allSellsCount": "1880",
        "goodComment": "81%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/04/17/d55857bf-78d8-4477-98ae-57fea92077f2_thumb.jpg",
        "title": "e家洁新居开荒",
        "description": "服务内容：1.开荒服务，按照建筑面积计费，50平米起购；...",
        "price": "10",
        "oldPrice": "10元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "e家洁",
        "allSellsCount": "1997",
        "goodComment": "84%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/30/2f3dabed-aea4-4e38-87ae-4022b0428e25_thumb.jpg",
        "title": "新房开荒",
        "description": "服务内容：1.120平米起订，家洁师携带工具，包括桶、毛巾...",
        "price": "8",
        "oldPrice": "11元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "保洁宝",
        "allSellsCount": "0",
        "goodComment": "100%",
        "arriveTime": "8小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/22/1d5266e2-dd91-4302-b1eb-826473a65b0b_thumb.jpg",
        "title": "8小时新居开荒保洁",
        "description": "8小时起订，服务人员携带七色保洁布、进口工具组、多用玻璃擦、...",
        "price": "799",
        "oldPrice": "959元",
        "discount": true,
        "unit": "元/次",
        "serveName": "爱家管家",
        "allSellsCount": "0",
        "goodComment": "66%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/07/4483d722-566f-4a1b-938c-2ab0219f1a49_thumb.jpg",
        "title": "开荒保洁1平方（30平起拍）",
        "description": "服务内容：开荒保洁，30平米起购，服务商携带专业开荒工具上...",
        "price": "8",
        "oldPrice": "10元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "来人到家",
        "allSellsCount": "4181",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/24/923ee63e-498f-4a22-808c-f3c18946a307_thumb.jpg",
        "title": "开荒保洁1平方（30平起拍）",
        "description": "服务内容：开荒保洁，30平米起购，服务商携带专业开荒工具上...",
        "price": "8",
        "oldPrice": "12元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "三鼎家政",
        "allSellsCount": "1554",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/afab6e2b-3d3c-4085-aad1-6d8313487688_thumb.jpg",
        "title": "新居专业开荒",
        "description": "服务内容：本服务产品属于装修后的首次开荒保洁，60平米起...",
        "price": "18",
        "oldPrice": "25元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "580家政网",
        "allSellsCount": "473",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/19/91b5677b-ee18-441f-85dc-7a9aced77b9b_thumb.jpg",
        "title": "新居开荒",
        "description": "所谓无忧开荒是装修后的首次开荒保洁，属于精细开荒，均由经过专...",
        "price": "9",
        "oldPrice": "9元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "家事无忧",
        "allSellsCount": "1",
        "goodComment": "100%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/07/26/4e09bd77-e161-494f-856d-cd32980a5660_thumb.jpg",
        "title": "对公开荒保洁",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "5.5",
        "oldPrice": "7.5元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "1880",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/1bc8113a-b68b-4be2-aee4-55f49a3075b1_thumb.jpg",
        "title": "140平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1399",
        "oldPrice": "1400元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/e8d7e9ed-e7e3-4bb3-b74d-1c89223fcd7d_thumb.jpg",
        "title": "150平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1499",
        "oldPrice": "1500元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "2",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/10/4774e0ec-ada3-4c2a-97de-212ca8cf8801_thumb.jpg",
        "title": "200平米开荒",
        "description": "随叫随到，送外窗玻璃清洁，专业技师、专业开荒设备新居入住开...",
        "price": "1999",
        "oldPrice": "2000元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/03/1d937c80-c243-4f17-b07e-c4a95992c22a_thumb.jpg",
        "title": "开荒保洁",
        "description": "服务内容：专业技师，专业设备，小圈为您提供最优秀的清洁服务...",
        "price": "10",
        "oldPrice": "10元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "250",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/05/16/78950d2b-132b-4953-b621-5db38685b52e_thumb.jpg",
        "title": "二手房开荒",
        "description": "服务内容：旧居开荒保洁服务，专业技师，专业设备，小圈为您提...",
        "price": "12",
        "oldPrice": "15元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "127",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/23/d177d0db-6d7b-41d2-8660-a6e61541b46c_thumb.jpg",
        "title": "新居精品开荒保洁",
        "description": "随叫随到，360度无死角精品开荒清洁自带所有工具和机器新...",
        "price": "12",
        "oldPrice": "15元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/06/15/1a8ffe69-dd9c-4a3c-ae86-cbdd702713fb_thumb.jpg",
        "title": "新居开荒",
        "description": "服务内容：新居装修入住前以及二手房翻新清洁，30平米起购（...",
        "price": "12",
        "oldPrice": "13元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "e家帮",
        "allSellsCount": "41",
        "goodComment": "87%",
        "arriveTime": "5小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/05/09/59e286bf-0f42-42d3-99ac-c93493a34f74_thumb.jpg",
        "title": "新居开荒保洁",
        "description": "服务内容：1.开荒服务按照建筑面积计算，60平米起订；...",
        "price": "8.8",
        "oldPrice": "12元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "e清洗",
        "allSellsCount": "1880",
        "goodComment": "81%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/04/17/d55857bf-78d8-4477-98ae-57fea92077f2_thumb.jpg",
        "title": "e家洁新居开荒",
        "description": "服务内容：1.开荒服务，按照建筑面积计费，50平米起购；...",
        "price": "10",
        "oldPrice": "10元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "e家洁",
        "allSellsCount": "1997",
        "goodComment": "84%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/11/30/2f3dabed-aea4-4e38-87ae-4022b0428e25_thumb.jpg",
        "title": "新房开荒",
        "description": "服务内容：1.120平米起订，家洁师携带工具，包括桶、毛巾...",
        "price": "8",
        "oldPrice": "11元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "保洁宝",
        "allSellsCount": "0",
        "goodComment": "100%",
        "arriveTime": "8小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/22/1d5266e2-dd91-4302-b1eb-826473a65b0b_thumb.jpg",
        "title": "8小时新居开荒保洁",
        "description": "8小时起订，服务人员携带七色保洁布、进口工具组、多用玻璃擦、...",
        "price": "799",
        "oldPrice": "959元",
        "discount": true,
        "unit": "元/次",
        "serveName": "爱家管家",
        "allSellsCount": "0",
        "goodComment": "66%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/6bb7be54-cb2b-4202-b889-51e0e35fa5fc_thumb.jpg",
        "title": "家庭深度保洁4小时",
        "description": "服务内容：家庭保洁，4小时/次，两个服务时间段：8：00-...",
        "price": "198",
        "oldPrice": "218元",
        "discount": true,
        "unit": "元/4小时",
        "serveName": "580家政网",
        "allSellsCount": "210",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/52d07f83-21b1-4f7b-bf86-a7b0e10bcbc0_thumb.jpg",
        "title": "4小时家庭保洁月卡 4次",
        "description": "4次高品质家庭保洁服务月卡，建议每周1次1、4次服务须在同...",
        "price": "598",
        "oldPrice": "848元",
        "discount": true,
        "unit": "元/月",
        "serveName": "580家政网",
        "allSellsCount": "6",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/05/26/1254a529-8ade-445f-9638-c7a157dd967a_thumb.jpg",
        "title": "厨房整体保洁",
        "description": "我们是TCL集团旗下家电服务品牌服务流程：1.现场环境观...",
        "price": "256",
        "oldPrice": "256元",
        "discount": false,
        "unit": "元/套",
        "serveName": "十分到家",
        "allSellsCount": "60",
        "goodComment": "96%",
        "arriveTime": "18小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/06/15/f1160a31-0c91-49ca-918d-0b3b6bea1a47_thumb.jpg",
        "title": "大扫除",
        "description": "服务内容：1.深度保洁，不留死角，适用于长时间未清洁的空间...",
        "price": "35",
        "oldPrice": "50元",
        "discount": true,
        "unit": "元/小时",
        "serveName": "e家帮",
        "allSellsCount": "679",
        "goodComment": "87%",
        "arriveTime": "5小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/08/a2cd0a2c-6b3c-445e-b604-f46eab91bf38_thumb.jpg",
        "title": "卫生间保养一套",
        "description": "服务内容：卫生间保养，工人携带专业工具上门服务。服务保...",
        "price": "390",
        "oldPrice": "390元",
        "discount": false,
        "unit": "元/次",
        "serveName": "三鼎家政",
        "allSellsCount": "3",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/08/c834cad2-683a-4070-9212-6e2e9637044a_thumb.jpg",
        "title": "厨房保养一套",
        "description": "服务内容：厨房保养，工人携带专业工具上门服务。服务保障...",
        "price": "450",
        "oldPrice": "690元",
        "discount": true,
        "unit": "元/次",
        "serveName": "三鼎家政",
        "allSellsCount": "3",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/06/23/e141c4a6-577e-4c0f-82d3-6bbb1443b62c_thumb.jpg",
        "title": "厨房保养一套",
        "description": "服务内容：厨房保养，工人携带专业工具上门服务。服务保障...",
        "price": "450",
        "oldPrice": "650元",
        "discount": true,
        "unit": "元/套",
        "serveName": "来人到家",
        "allSellsCount": "42",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/06/23/ff90ba89-553c-43da-878b-4ccbe7834003_thumb.jpg",
        "title": "卫生间保养一套",
        "description": "服务内容：卫生间保养，工人携带专业工具上门服务。服务保...",
        "price": "239",
        "oldPrice": "340元",
        "discount": true,
        "unit": "元/套",
        "serveName": "来人到家",
        "allSellsCount": "93",
        "goodComment": "85%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/09/29/a75092aa-c70c-4638-b42b-5f46c76d9afb_thumb.jpg",
        "title": "厨房整体深度清洁（家庭保洁）",
        "description": "服务内容：1.立体式。（五面，两柜，两玻，不秀钢等等）五...",
        "price": "368",
        "oldPrice": "415元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家电好师傅",
        "allSellsCount": "0",
        "goodComment": "100%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/265f92a2-331e-4166-a474-14c9fafd97e8_thumb.jpg",
        "title": "4小时家庭保洁季卡  6次服务",
        "description": "6次高品质家庭保洁服务，建议2周1次1、6次服务须在同一地...",
        "price": "1148",
        "oldPrice": "1248元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "1",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/f43b1902-c1c2-4385-9bc2-bbb67c47da7d_thumb.jpg",
        "title": "4小时家庭保洁季卡 12次服务",
        "description": "12次高品质家庭保洁服务，建议1周1次1、12次服务须在同...",
        "price": "2168",
        "oldPrice": "2408元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/07/7f0776b9-f9de-429b-a053-46828594e95d_thumb.jpg",
        "title": "4小时家庭保洁季卡  24次",
        "description": "24次高品质家庭保洁服务，建议1周2次1、24次服务须在同...",
        "price": "4188",
        "oldPrice": "4808元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "1",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/03/09/e372406e-3c7e-4c8e-a89e-4f0d0cd21766_thumb.jpg",
        "title": "4小时家庭保洁年卡  48次",
        "description": "48次高品质家庭保洁服务，建议1周1次1、48次服务须在同...",
        "price": "7998",
        "oldPrice": "9208元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/916a33f6-1884-4d19-a9ca-15d7cfe797f0_thumb.jpg",
        "title": "卫生间一站式深度保洁 升级版",
        "description": "服务人员：专职保洁师服务时间：上午8:00-12:00或...",
        "price": "229",
        "oldPrice": "299元",
        "discount": true,
        "unit": "元/次",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/09/01/13946f92-8ab6-4462-ab20-77338ff2b08f_thumb.jpg",
        "title": "1580元大直抵5360元礼包",
        "description": "礼包详情：价值1580元的服务礼包，下列3项产品任选4次，...",
        "price": "1580",
        "oldPrice": "5360元",
        "discount": true,
        "unit": "元/套",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/26/26da570c-2f99-4e64-8cb5-0db501e1ac59_thumb.jpg",
        "title": "厨房深度清洁",
        "description": "服务介绍：采用专业保洁工具、高温消毒杀菌设备，针对天花、墙面...",
        "price": "299",
        "oldPrice": "399元",
        "discount": true,
        "unit": "元/次",
        "serveName": "580家政网",
        "allSellsCount": "0",
        "goodComment": "98%",
        "arriveTime": "12小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/06/44dca981-73b9-49bb-8a4c-f545c17afb10_thumb.jpg",
        "title": "厨房整体深度清洁",
        "description": "下单服务：预约维修后洁修哥客服将在15分钟内联系客户，与客...",
        "price": "559",
        "oldPrice": "599元",
        "discount": true,
        "unit": "元/次",
        "serveName": "洁修哥",
        "allSellsCount": "0",
        "goodComment": "99%",
        "arriveTime": "2小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/19/d78ae963-1d00-468a-b4c8-8e94006c1d4d_thumb.jpg",
        "title": "家政保洁-单人4小时",
        "description": "保洁师自带整套工具上门服务。服务时间段：8:00-12:0...",
        "price": "199",
        "oldPrice": "299元",
        "discount": true,
        "unit": "元/次",
        "serveName": "轻喜到家",
        "allSellsCount": "0",
        "goodComment": "100%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/19/1351e8a3-13d9-40c0-bc51-7d052322b800_thumb.jpg",
        "title": "家庭保洁 一月三次",
        "description": "4小时/次，保洁师自带整套工具上门服务。服务时间段：8:0...",
        "price": "299",
        "oldPrice": "599元",
        "discount": true,
        "unit": "元/套",
        "serveName": "轻喜到家",
        "allSellsCount": "0",
        "goodComment": "100%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/09/27/16bc595d-e8e3-4efe-bb38-428cedfaadd1_thumb.jpg",
        "title": "厨房深度清洁保养套餐",
        "description": "服务时长：共300分钟（150分钟/2人）清洗保养范围...",
        "price": "439",
        "oldPrice": "520元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家电小哥",
        "allSellsCount": "3",
        "goodComment": "94%",
        "arriveTime": "24小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/09/05/28eedb15-d41a-4278-97ba-a2b92168eb89_thumb.jpg",
        "title": "三居室（2卫）深度清洁",
        "description": "随叫随到，360度无死角深度清洁高温蒸汽消毒杀菌，呵护家人...",
        "price": "1349",
        "oldPrice": "1499元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "25",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/07/31/b2c69720-ce20-45f1-bf35-0673032ea685_thumb.jpg",
        "title": "水磨石翻新、结晶",
        "description": "石材用相关化工药剂翻新养护已经不是一个新鲜的话题，目前国内石...",
        "price": "40",
        "oldPrice": "9元",
        "discount": false,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "301",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/01/11/da0e651f-0ebb-4760-b0b5-21a8d1fb2348_thumb.jpg",
        "title": "二手房极致清洁消毒",
        "description": "随叫随到，360度无死角深度清洁高温蒸汽消毒杀菌，呵护家人...",
        "price": "25",
        "oldPrice": "35元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2016/12/09/00522c9f-d3fb-483b-8746-170e7e71c71f_thumb.jpg",
        "title": "厨房卫生间深度保养一套",
        "description": "随叫随到，360度无死角深度清洁高温蒸汽消毒杀菌，呵护家人...",
        "price": "599",
        "oldPrice": "1080元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "10",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/21/072e127a-d988-43b1-9d44-8de065b01c3a_thumb.jpg",
        "title": "大复式房深度清洁",
        "description": "随叫随到，360度无死角深度清洁彻底清除居室中积累的灰尘、...",
        "price": "1999",
        "oldPrice": "2199元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/22/ea70bf03-e28b-4f17-b3ce-d5cc47c5fa3b_thumb.jpg",
        "title": "软包房清洗",
        "description": "软包房清洗",
        "price": "10",
        "oldPrice": "17元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/21/1c76601f-6465-4e00-8728-06c1d4122f0b_thumb.jpg",
        "title": "小复式房深度清洁",
        "description": "随叫随到，360度无死角深度清洁高温蒸汽消毒杀菌，呵护家人...",
        "price": "1099",
        "oldPrice": "1199元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/06/13/dbe35626-6714-422a-9cf9-a2b8da4df437_thumb.jpg",
        "title": "三小时保洁29次/年卡",
        "description": "服务内容：家庭保洁服务3小时（29次/3小时/每人/每年）...",
        "price": "3199",
        "oldPrice": "4499元",
        "discount": true,
        "unit": "元/次",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/05/16/af1ed65f-95c9-4ab4-b102-9cf5f158b459_thumb.jpg",
        "title": "商务办公楼保洁",
        "description": "服务内容：商务办公楼保洁服务，专业技师，专业设备，小圈保洁...",
        "price": "5",
        "oldPrice": "8元",
        "discount": true,
        "unit": "元/平米",
        "serveName": "家政圈",
        "allSellsCount": "0",
        "goodComment": "86%",
        "arriveTime": "1小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/04/17/87725126-64f6-4bf0-912c-1baa6a9c98be_thumb.jpg",
        "title": "e家洁厨房高温保洁",
        "description": "服务内容：专业的厨房高温保洁服务，使用德国进口消毒设备进行...",
        "price": "450",
        "oldPrice": "450元",
        "discount": false,
        "unit": "元/间",
        "serveName": "e家洁",
        "allSellsCount": "2",
        "goodComment": "84%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/2017/04/17/12d3c054-3e6e-43d9-896f-a383d8e020ca_thumb.jpg",
        "title": "e家洁卫生间保洁",
        "description": "服务内容：专业的卫生间高温保洁服务，使用进口消毒设备进行卫...",
        "price": "240",
        "oldPrice": "240元",
        "discount": false,
        "unit": "元/间",
        "serveName": "e家洁",
        "allSellsCount": "3",
        "goodComment": "84%",
        "arriveTime": "4小时"
      },
      {
        "imgUrl": "http://img.daoway.cn/img/price/2017/08/22/819bb72a-11bd-4573-bc28-9e7bb3a13960_thumb.jpg",
        "title": "8小时深度保洁",
        "description": "8小时起订，服务人员携带七色保洁布、进口工具组、多用玻璃擦、...",
        "price": "459",
        "oldPrice": "559元",
        "discount": true,
        "unit": "元/次",
        "serveName": "爱家管家",
        "allSellsCount": "0",
        "goodComment": "66%",
        "arriveTime": "4小时"
      }
    ]

    }
  }

  var data1=data.classification.data
  console.log(data1.length)

 $.each()



})